name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build-webos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download webOS NDK
        uses: robinraju/release-downloader@v1.9
        with:
          repository: "openlgtv/buildroot-nc4"
          latest: true
          fileName: "arm-webos-linux-gnueabi_sdk-buildroot.tar.gz"
          out-file-path: "/tmp"

      - name: Extract and relocate webOS NDK
        shell: bash
        working-directory: /tmp
        run: |
          tar xzf arm-webos-linux-gnueabi_sdk-buildroot.tar.gz
          ./arm-webos-linux-gnueabi_sdk-buildroot/relocate-sdk.sh

      - name: Build
        env:
          TOOLCHAIN_FILE: /tmp/arm-webos-linux-gnueabi_sdk-buildroot/usr/share/buildroot/toolchainfile.cmake
        run: ./tools/webos/easy_build.sh -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ihsplay-webos
          path: dist/*.ipk
